#!/usr/bin/env bash

clear

read -p "Digite o seu nome: " nome
echo "Olá, usuário $nome\n"

echo "Essas informações são muito importantes"
echo "---------------------------------------"
echo -n "Usuário : "
whoami
echo -n "Hostname: "
hostname
echo -n "Uptime  : "
uptime -p
echo -n "Kernel  : "
uname -rms
echo "---------------------------------------\n"

