#!/usr/bin/env bash
# --------------------------------------------------
# Script   : pegadinha
# Descrição: Exercício de concatenação de Strings
# Versão   : 1.0
# Autor    : Augusto Alves Frazão
# Data     : 20 de Feb de 2026 23:16:11
# Licença  : GUN/GPL v3.0
# --------------------------------------------------
# Uso: Concatenação de Strings
# --------------------------------------------------

clear

read -p "Digite um nome: " nome

read -p "Digite o nome de uma revista: " revista

read -p "Digite o nome de uma peça de roupa: " roupa

echo "
Você escolheu: $nome, $revista e $roupa.
"

read -p "Escolha um número de 1 a 3: " number

frase[1]="$nome saiu na capa da revista $revista só de $roupa!"
frase[2]="$nome só ler revista $revista vestido de $roupa."
frase[3]="$nome leu a revista $revista para escolha a $roupa!"

echo "
${frase[$number]}
"

exit 0
